name: Scheduled Notion Data Fetch

on:
    schedule:
        - cron: '0 15 * * *' # actions at midnight every day
    workflow_dispatch: # Allows manual triggering on GitHub UI

jobs:
    fetch-and-update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run the fetch and update script
              env:
                  NOTION_KEY: ${{ secrets.NOTION_KEY }}
              run: npx ts-node ./scripts/fetchNotionData.ts

            - name: Check for changes
              id: git_diff
              run: |
                  git fetch origin
                  echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
                  if ! git diff --exit-code public/history.json; then
                    echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
                  fi
                  if ! git diff --exit-code public/recruit.json; then
                    echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
                  fi

            - name: Commit changes
              if: env.CHANGES_DETECTED == 'true'
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add public/history.json public/recruit.json
                  git commit -m 'Update Notion data from GitHub Action'

            - name: Push changes
              if: env.CHANGES_DETECTED == 'true'
              uses: ad-m/github-push-action@v0.6.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: main

            - name: Trigger next workflow
              if: env.CHANGES_DETECTED == 'true'
              run: |
                curl -X POST \
                  -H "Accept: application/vnd.github.v3+json" \
                  -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  https://api.github.com/repos/${{ github.repository }}/dispatches \
                  -d '{"event_type":"deploy_workflow"}'