name: Scheduled Notion Data Fetch

on:
  schedule:
    - cron: '0 15 * * *' # actions at midnight every day
  workflow_dispatch: # Allows manual triggering on GitHub UI

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run the fetch and update script
      env:
        NOTION_KEY: ${{ secrets.NOTION_KEY }}
      run: npx ts-node ./scripts/fetchNotionData.ts